---
kind: pipeline
type: kubernetes
name: default

steps:
- name: setup_tools
  image: golang:1.15.6
  commands:
  - go get -u gotest.tools/gotestsum
  - go get -u github.com/go-bindata/go-bindata/...
  - make go-build
  - make go-test
---
kind: signature
hmac: f5e9900ad26adc5485dc322d08bd29ff617b6ca71ae7d5ff1aca833ee130fb7d

...
