---
kind: pipeline
type: kubernetes
name: default

steps:
- name: setup_tools
  image: golang:1.15.6
  commands:
  - go get -u gotest.tools/gotestsum
  - go get -u github.com/go-bindata/go-bindata/...
  - make build
  - make test
---
kind: signature
hmac: 745ead3e922e0a65cbba53f4a8dbe6db358bbbec0531e8e734a1816536d48c97

...
