---
kind: pipeline
type: kubernetes
name: default

steps:
  - name: restore-cache-with-filesystem
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./go-bin
    volumes:
    - name: cache
      path: /cache
  
  - name: build_and_test
    image: golang:1.15.6
    commands:
    # If no cache found with the tools, download them
    - "[ ! -f go-bin/go-bindata ] && go get -u gotest.tools/gotestsum"
    - "[ ! -f go-bin/gotestsum ] && go get -u github.com/go-bindata/go-bindata/..."
    # Make a go-bin directory if none exists
    - mkdir -p go-bin
    # Copy tools binaries into the local bin path
    - "[ ! -f go-bin/go-bindata ] && cp $GOPATH/bin/go-bindata go-bin/."
    - "[ ! -f go-bin/gotestsum ] && cp $GOPATH/bin/gotestsum go-bin/."
    # Builds & Tests the code
    - make go-build GO-BIN-FOLDER=go-bin/ GOOS=darwin GOARCH=amd64 BINARY_NAME=darwin-plonk
    - make go-build GO-BIN-FOLDER=go-bin/ GOOS=linux GOARCH=amd64 BINARY_NAME=linux-plonk
    - make go-test GO-BIN-FOLDER=go-bin/

  - name: rebuild-cache-with-filesystem
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./go-bin
    volumes:
    - name: cache
      path: /cache

  - name: publish
    image: plugins/github-release
    settings:
      api_key:
        from_secret: github_token
      files:
        - bin/*
      checksum:
        - md5
        - sha1
        - sha256
        - sha512
        - adler32
        - crc32
    when:
      event: tag

  - name: publish-deployer
    image: plugins/docker
    settings:
      registry: 
        from_secret: DOCKER_REGISTRY
      username:
        from_secret: DOCKER_USER
      password:
        from_secret: DOCKER_PASS
      repo:
        from_secret: DOCKER_REGISTRY/IMAGE_NAME
      dockerfile: Dockerfile.deployer
      when:
        event: tag


volumes:
- name: cache
  host:
    path: /tmp/drone/cache

---
kind: signature
hmac: 920e0c79a152fb46e38402c95368d5d988649cdb323834e12fe960c073e05ac3

...
