name: base
origin:
  - base/plonk.yaml
variables: 
  - base/base.yaml
  - base/custom.yaml
  - base/production.yaml
manifests:
  - base/ingress.yaml
  - base/main-deployment.yaml
  - base/service.yaml
