name: Go

on:
  push:
    branches: [ base ]
  pull_request:
    branches: [ base ]

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run tests
      run: make test INTERACTIVE=""

    - name: JUnit Report
      uses: mikepenz/action-junit-report@v1.1.1
      with:
        github_token: ${{ secrets.TOKEN }}
        report_paths: unit-tests.xml
