name: Go

on:
  push:
    branches: [ base ]
  pull_request:
    branches: [ base ]

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run tests
      run: make test INTERACTIVE=""
