name: Go

on:
  push:
    branches: [ base ]
  pull_request:
    branches: [ base ]

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest
    steps:

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Run tests
      run: make test INTERACTIVE=""

    - name: Publish Unit Test Results
      uses: docker://ghcr.io/enricomi/publish-unit-test-result-action:v1.6
      if: always()
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        files: '**/unit-tests.xml'
